### ISSUE TITLE
Fix issue where package crashes app on undefined  config.pages.some

### ISSUE THREAD

**Issue by Stefanpgr** [cjayprime/react-native-dojah#7]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-dojah@0.3.3` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-dojah/lib/Dojah.js b/node_modules/react-native-dojah/lib/Dojah.js
index 3e7d42c..8c8eada 100644
--- a/node_modules/react-native-dojah/lib/Dojah.js
+++ b/node_modules/react-native-dojah/lib/Dojah.js
@@ -84,7 +84,7 @@ const Dojah = ({
     [pages, type],
   );
   const needsLocation = useMemo(() => {
-    return config.pages.some(
+    return config?.pages?.some(
       (page) =>
         page.page === 'address' &&
         (typeof page.config?.verification === undefined ||
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by YemmyFolayan** [comment]
Thanks Stefan, We will  attend to this issue

**Comment by YemmyFolayan** [comment]
Thanks Stefan, We will  attend to this issue
